/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/gogo.glb -k -K -j -m -T 
Files: public/gogo.glb [1.33KB] > /Users/peterskills/Desktop/react-three-fiber/my-app/gogo-transformed.glb [1KB] (25%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/gogo-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh name="HouseMain001" geometry={nodes.HouseMain001.geometry} material={nodes.HouseMain001.material} position={[-0.446, 4.705, 0.067]} userData={{ name: 'HouseMain.001' }} />
      </group>
    </group>
  )
}

useGLTF.preload('/gogo-transformed.glb')
