/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/gogo.glb -k -K -j -m -T 
Files: public/gogo.glb [1.33KB] > /Users/peterskills/Desktop/react-three-fiber/my-app/gogo-transformed.glb [1KB] (25%)
*/

import { useGLTF, useTexture } from "@react-three/drei";
import React from "react";
import { editable as e } from "@theatre/r3f";

export function Bakery(props) {
	const { nodes } = useGLTF("/baking.glb");

	const bakedTexture = useTexture("/guccigang.jpg");

	bakedTexture.flipY = false;

	const tilesTexture = useTexture("/tiles.jpg");

	tilesTexture.flipY = false;

	const cakeTexture = useTexture("/baking.jpg");

	cakeTexture.flipY = false;

	return (
		<group position-y={-1} {...props} dispose={null}>
			<mesh geometry={nodes.Node.geometry} position={[0.169, 1.233, -1.532]}>
				<meshBasicMaterial map={cakeTexture} />
			</mesh>
			<mesh
				geometry={nodes.donutSprinkles.geometry}
				position={[0.383, 1.161, 1.091]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.donutSprinkles001.geometry}
				position={[0.216, 1.161, 1.23]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.donutSprinkles002.geometry}
				position={[0.536, 1.161, 1.281]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.donutSprinkles003.geometry}
				position={[0.363, 1.161, 1.4]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.donutSprinkles004.geometry}
				position={[-0.458, 1.161, 1.131]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.donutSprinkles005.geometry}
				position={[-0.244, 1.161, 1.131]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.donutSprinkles006.geometry}
				position={[-0.244, 1.161, 1.413]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.donutSprinkles007.geometry}
				position={[-0.458, 1.161, 1.393]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.Honey.geometry}
				position={[-1.765, 2.675, -0.523]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallFrame.geometry}
				position={[-1.885, 2.387, 1.015]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.Honey001.geometry}
				position={[-1.288, 2.668, -1.798]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.Honey002.geometry}
				position={[-0.863, 2.668, -1.798]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.Honey003.geometry}
				position={[-0.863, 2.316, -1.798]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.Honey004.geometry}
				position={[-1.307, 2.316, -1.798]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.Honey005.geometry}
				position={[-1.765, 2.675, -1.018]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.Honey006.geometry}
				position={[-1.765, 2.324, -1.018]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.Honey007.geometry}
				position={[-1.765, 2.324, -0.571]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.BreadShelf.geometry}
				position={[-1.672, 1.351, 0.368]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.loafBaguette002.geometry}
				position={[-1.614, 1.509, 0.172]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.Loaf2001.geometry}
				position={[-1.645, 1.904, 0.478]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.Loaf2002.geometry}
				position={[-1.645, 1.904, 0.227]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.Loaf2003.geometry}
				position={[-1.585, 1.166, 0.544]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.Loaf2004.geometry}
				position={[-1.585, 1.166, 0.333]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.Loaf2005.geometry}
				position={[-1.585, 1.166, 0.142]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.loafBaguette001.geometry}
				position={[-1.614, 1.509, 0.351]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.loafBaguette003.geometry}
				position={[-1.614, 1.509, 0.572]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh geometry={nodes.Cake1.geometry} position={[1.122, 1.233, 1.27]}>
				<meshBasicMaterial map={cakeTexture} />
			</mesh>
			<mesh
				geometry={nodes.Cake1001.geometry}
				position={[1.122, 1.233, 0.609]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.Cabinet_FrontA006_Material_0002.geometry}
				position={[-0.19, 1.14, -1.552]}
			>
				<meshBasicMaterial map={cakeTexture} />
			</mesh>
			<mesh geometry={nodes.Oven.geometry} position={[0.737, 1.125, -1.32]}>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.Plate.geometry}
				position={[-1.468, 1.252, -0.615]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.Rolling_Pin_Q.geometry}
				position={[-1.248, 1.272, -1.529]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.CookingEdeny.geometry}
				position={[-1.607, 1.372, -1.397]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.Plate001.geometry}
				position={[0.379, 1.138, 1.269]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.Plate002.geometry}
				position={[-0.351, 1.135, 1.269]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh geometry={nodes.chair.geometry} position={[3.507, 0.306, 1.844]}>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.chair001.geometry}
				position={[3.507, 0.306, -0.163]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh castShadow receiveShadow geometry={nodes.Terrain.geometry}>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.EntranceTile1.geometry}
				position={[1.308, 0.037, 1.95]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.EntranceTile2.geometry}
				position={[1.823, 0.037, 1.95]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.EntranceTile3.geometry}
				position={[1.308, 0.037, 2.457]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.EntranceTile4.geometry}
				position={[1.854, 0.037, 2.457]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.EntranceTile5.geometry}
				position={[1.284, 0.037, 2.974]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.EntranceTile6.geometry}
				position={[1.854, 0.037, 2.974]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.EntranceTile7.geometry}
				position={[1.271, 0.037, 3.487]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.EntranceTile8.geometry}
				position={[1.832, 0.037, 3.487]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.HouseWall1.geometry}
				position={[-0.347, 1.653, -2.045]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.HouseWall2.geometry}
				position={[-2, 1.653, -0.135]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.Wall_teteje2.geometry}
				position={[-2.006, 3.164, -0.087]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallAlso.geometry}
				position={[-0.264, 0.106, -0.137]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallJobbAlsoAlso.geometry}
				position={[-0.264, 0.106, -2.044]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallJobbAlsoAlso001.geometry}
				position={[-2.001, 0.106, -0.22]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTeteje1.geometry}
				position={[-0.309, 3.164, -2.045]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.HouseFloor.geometry}
				position={[-0.263, 0.27, -0.137]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles01.geometry}
				position={[1.303, 1.4, -1.955]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles02.geometry}
				position={[1.303, 1.205, -1.955]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles03.geometry}
				position={[1.303, 1.01, -1.955]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles04.geometry}
				position={[1.303, 0.815, -1.955]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles05.geometry}
				position={[1.303, 0.621, -1.955]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles06.geometry}
				position={[1.303, 0.426, -1.955]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles0007.geometry}
				position={[-1.904, 1.4, 1.637]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles0008.geometry}
				position={[-1.904, 1.205, 1.637]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles0009.geometry}
				position={[-1.904, 1.01, 1.637]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles0010.geometry}
				position={[-1.904, 0.815, 1.637]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles0011.geometry}
				position={[-1.904, 0.621, 1.637]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles0012.geometry}
				position={[-1.904, 0.426, 1.637]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1.geometry}
				position={[-1.909, 1.4, 1.379]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1001.geometry}
				position={[-1.909, 1.4, 0.987]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1002.geometry}
				position={[-1.909, 1.4, 0.595]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1003.geometry}
				position={[-1.909, 1.4, 0.204]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1004.geometry}
				position={[-1.909, 1.4, -0.188]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1005.geometry}
				position={[-1.909, 1.4, -0.58]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1006.geometry}
				position={[-1.909, 1.4, -0.972]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1007.geometry}
				position={[-1.909, 1.4, -1.364]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1008.geometry}
				position={[-1.909, 1.4, -1.756]}
			>
				{" "}
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1009.geometry}
				position={[-1.909, 1.205, 1.379]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1010.geometry}
				position={[-1.909, 1.205, 0.987]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1011.geometry}
				position={[-1.909, 1.205, 0.595]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1012.geometry}
				position={[-1.909, 1.205, 0.204]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1013.geometry}
				position={[-1.909, 1.205, -0.188]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1014.geometry}
				position={[-1.909, 1.205, -0.58]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1015.geometry}
				position={[-1.909, 1.205, -0.972]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1016.geometry}
				position={[-1.909, 1.205, -1.364]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1017.geometry}
				position={[-1.909, 1.205, -1.756]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1018.geometry}
				position={[-1.909, 1.01, 1.379]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1019.geometry}
				position={[-1.909, 1.01, 0.987]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1020.geometry}
				position={[-1.909, 1.01, 0.595]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1021.geometry}
				position={[-1.909, 1.01, 0.204]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1022.geometry}
				position={[-1.909, 1.01, -0.188]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1023.geometry}
				position={[-1.909, 1.01, -0.58]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1024.geometry}
				position={[-1.909, 1.01, -0.972]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1025.geometry}
				position={[-1.909, 1.01, -1.364]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1026.geometry}
				position={[-1.909, 1.01, -1.756]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1027.geometry}
				position={[-1.909, 0.815, 1.379]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1028.geometry}
				position={[-1.909, 0.815, 0.987]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1029.geometry}
				position={[-1.909, 0.815, 0.595]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1030.geometry}
				position={[-1.909, 0.815, 0.204]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1031.geometry}
				position={[-1.909, 0.815, -0.188]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1032.geometry}
				position={[-1.909, 0.815, -0.58]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1033.geometry}
				position={[-1.909, 0.815, -0.972]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1034.geometry}
				position={[-1.909, 0.815, -1.364]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1035.geometry}
				position={[-1.909, 0.815, -1.756]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1036.geometry}
				position={[-1.909, 0.621, 1.379]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1037.geometry}
				position={[-1.909, 0.621, 0.987]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1038.geometry}
				position={[-1.909, 0.621, 0.595]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1039.geometry}
				position={[-1.909, 0.621, 0.204]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1040.geometry}
				position={[-1.909, 0.621, -0.188]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1041.geometry}
				position={[-1.909, 0.621, -0.58]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1042.geometry}
				position={[-1.909, 0.621, -0.972]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1043.geometry}
				position={[-1.909, 0.621, -1.364]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1044.geometry}
				position={[-1.909, 0.621, -1.756]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1045.geometry}
				position={[-1.909, 0.426, 1.379]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1046.geometry}
				position={[-1.909, 0.426, 0.987]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1047.geometry}
				position={[-1.909, 0.426, 0.595]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1048.geometry}
				position={[-1.909, 0.426, 0.204]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1049.geometry}
				position={[-1.909, 0.426, -0.188]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1050.geometry}
				position={[-1.909, 0.426, -0.58]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1051.geometry}
				position={[-1.909, 0.426, -0.972]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1052.geometry}
				position={[-1.909, 0.426, -1.364]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles1053.geometry}
				position={[-1.909, 0.426, -1.756]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2.geometry}
				position={[-1.759, 1.4, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2001.geometry}
				position={[-1.446, 1.4, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2002.geometry}
				position={[-1.132, 1.4, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2003.geometry}
				position={[-0.819, 1.4, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2004.geometry}
				position={[-0.505, 1.4, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2005.geometry}
				position={[-0.192, 1.4, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2006.geometry}
				position={[0.122, 1.4, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2007.geometry}
				position={[0.436, 1.4, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2008.geometry}
				position={[0.749, 1.4, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2009.geometry}
				position={[-1.759, 1.205, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2010.geometry}
				position={[-1.446, 1.205, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2011.geometry}
				position={[-1.132, 1.205, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2012.geometry}
				position={[-0.819, 1.205, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2013.geometry}
				position={[-0.505, 1.205, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2014.geometry}
				position={[-0.192, 1.205, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2015.geometry}
				position={[0.122, 1.205, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2016.geometry}
				position={[0.436, 1.205, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2017.geometry}
				position={[0.749, 1.205, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2018.geometry}
				position={[-1.759, 1.01, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2019.geometry}
				position={[-1.446, 1.01, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2020.geometry}
				position={[-1.132, 1.01, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2021.geometry}
				position={[-0.819, 1.01, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2022.geometry}
				position={[-0.505, 1.01, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2023.geometry}
				position={[-0.192, 1.01, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2024.geometry}
				position={[0.122, 1.01, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2025.geometry}
				position={[0.436, 1.01, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2026.geometry}
				position={[0.749, 1.01, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2027.geometry}
				position={[-1.759, 0.815, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2028.geometry}
				position={[-1.446, 0.815, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2029.geometry}
				position={[-1.132, 0.815, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2030.geometry}
				position={[-0.819, 0.815, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2031.geometry}
				position={[-0.505, 0.815, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2032.geometry}
				position={[-0.192, 0.815, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2033.geometry}
				position={[0.122, 0.815, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2034.geometry}
				position={[0.436, 0.815, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2035.geometry}
				position={[0.749, 0.815, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2036.geometry}
				position={[-1.759, 0.621, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2037.geometry}
				position={[-1.446, 0.621, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2038.geometry}
				position={[-1.132, 0.621, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2039.geometry}
				position={[-0.819, 0.621, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2040.geometry}
				position={[-0.505, 0.621, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2041.geometry}
				position={[-0.192, 0.621, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2042.geometry}
				position={[0.122, 0.621, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2043.geometry}
				position={[0.436, 0.621, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2044.geometry}
				position={[0.749, 0.621, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2045.geometry}
				position={[-1.759, 0.426, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2046.geometry}
				position={[-1.446, 0.426, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2047.geometry}
				position={[-1.132, 0.426, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2048.geometry}
				position={[-0.819, 0.426, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2049.geometry}
				position={[-0.505, 0.426, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2050.geometry}
				position={[-0.192, 0.426, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2051.geometry}
				position={[0.122, 0.426, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2052.geometry}
				position={[0.436, 0.426, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2053.geometry}
				position={[0.749, 0.426, -1.961]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2054.geometry}
				position={[1.062, 1.4, -1.955]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2055.geometry}
				position={[1.062, 1.205, -1.955]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2056.geometry}
				position={[1.062, 1.01, -1.955]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2057.geometry}
				position={[1.062, 0.815, -1.955]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2058.geometry}
				position={[1.062, 0.621, -1.955]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.WallTiles2059.geometry}
				position={[1.062, 0.426, -1.955]}
			>
				<meshBasicMaterial map={tilesTexture} />
			</mesh>
			<mesh
				geometry={nodes.ModernKitchenTable1.geometry}
				position={[-0.092, 0.894, 1.246]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.ModernKitchenTable1001.geometry}
				position={[1.042, 0.889, 0.905]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.Cabinet_new.geometry}
				position={[-1.12, 2.28, -1.821]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.Cabinet_Shelf_B007_Material_0.geometry}
				position={[-1.773, 2.28, -0.815]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.CabinetTable_B002_Material_0001.geometry}
				position={[-1.389, 0.865, -1.008]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes["38_Kitche1001"].geometry}
				position={[-0.809, 1.429, -1.653]}
			>
				<meshBasicMaterial map={cakeTexture} />
			</mesh>
			<mesh
				geometry={nodes.FlowerPot4.geometry}
				position={[-1.4, 1.086, 1.47]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh
				geometry={nodes.Window.geometry}
				position={[0.211, 2.105, -1.901]}
			>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
			<mesh geometry={nodes.Table.geometry} position={[3.586, 0.097, 0.799]}>
				<meshBasicMaterial map={bakedTexture} />
			</mesh>
		</group>
	);
}

useGLTF.preload("/baking.glb");
